---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This is simple Hello World component written in Java."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    Message: "Hello from Java!"
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        "com.example.JavaMqttHello:mqttproxy:1":
          policyDescription: "Allows access to publish to all topics."
          operations:
            - "aws.greengrass#PublishToIoTCore"
          resources:
            - "*"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/JavaMqttHello-1.0.0.jar"
    Lifecycle:
      Run: "java -cp {artifacts:path}/JavaMqttHello-1.0.0.jar com.hello.App \"{configuration:/Message}\""